### ISSUE TITLE
Install the plugin fail

### ISSUE THREAD

**Issue by nchaulet** [logstash-plugins/logstash-output-google_bigquery#21]
Install the plugin fail with the following message:
`Make sure that `gem install google-api-client -v '0.9.9'` succeeds before bundling.`

![screen shot 2016-07-05 at 3 52 16 pm](https://cloud.githubusercontent.com/assets/1336873/16597757/89e49bc6-42c8-11e6-99cb-df385bbd6b2f.png)

- Version: logstash 2.3
- Operating System: Tested on OS X and the official logstash docker container
- Steps to Reproduce: `logstash-plugin install logstash-output-google_bigquery`

**Comment by permyakovsv** [comment]
Tha same issue.((

**Comment by alexpx** [comment]
+1

**Comment by jsvd** [comment]
interesting..the plugin, clearly depends on google-api-client 0.8.7 (https://rubygems.org/gems/logstash-output-google_bigquery/versions/3.0.0), yet still it tried to install version 0.9.x, which is only compatible with ruby 2.x

**Comment by alexpx** [comment]
Thanks for the quick fix.
