### ISSUE TITLE
Use the Streaming API

### ISSUE THREAD

**Issue by josephlewis42** [logstash-plugins/logstash-output-google_bigquery#36]
Let's batch up requests and use the [streaming API](https://cloud.google.com/bigquery/streaming-data-into-bigquery#bigquery-stream-data-java) to upload. 

This will eliminate the need for multiple queues, recovery, locking, and temporary files. In addition, using LogStash to hold data to be uploaded rather than an internal queue means we can take advantage of its backpressure and disk-based queue/recovery instead of implementing it ourselves.

**Comment by colinsurprenant** [comment]
ahah this issue description is completely different from the email notification I received - that was confusing. 

+1 on the strategy.

**Comment by josephlewis42** [comment]
@colinsurprenant sorry about that, I wrote something out then modified it once I remembered we had the streaming API :-)

I've got a PR in now that fixes this and should close 9 or 10 of the open issues/PRs in this repo.

**Comment by josephlewis42** [comment]
The fix for this has been released as part of logstash-output-google_bigquery version 4.0.0. 

**WARNING** 4.0.0 has breaking changes so [read the changelog](https://github.com/logstash-plugins/logstash-output-google_bigquery/blob/master/CHANGELOG.md) before upgrading to understand how they'll affect you.

The plugin can be updated with the following command

```
bin/logstash-plugin update logstash-output-google_bigquery
```
