### ISSUE TITLE
BigQuery output plugin doesn't load all rows into table from source

### ISSUE THREAD

**Issue by SrikrishnaBingi** [logstash-plugins/logstash-output-google_bigquery#51]
Hello,

This is w.r.t to my discussion post in logstash forum - https://discuss.elastic.co/t/logstash-es-to-bigquery-doesnt-load-all-rows-into-bigquery/190114

- Version: Logstash 7.1.1
- Operating System: Mac 
- Steps to Reproduce:
Ran logstash job for specified config file with default parameters

**Background:**
Long story short - My logstash job runs successfully but doesn't load all the rows into bigquery table from source.  I analyzed that my input plugin and filter plugin do not filter out valid records. As mentioned in forum post, the total number of records in source is 11437 whereas the total number of records committed using default setting is 11392, and the number of records that haven't been loaded is 45. By default, the batch_size is 128; I changed this setting and other settings provided but somehow couldn't load all the data from source.

I observed that the logstash loads data in multiples of the batch size specified (11392 is 89*128) and "drops" the last bunch which are left out by batch processing( 11437 - 11392 = 45*). This happened not only with the table specified in the forum but also with several others.

**Fix:**
By reverse engineering the logstash output log, I figured out that the method "enqueue" in "Batcher.rb" gem works in tandem with method "publish" in "google_bigquery.rb" gem to stream incoming records to bigquery table. Depending on the "[batch size](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-google_bigquery.html#plugins-outputs-google_bigquery-batch_size)", the plugin would group incoming records into batches and insert them into bigquery tables.

In order to ensure that all records are processed, I did the following:

1. Passed in the total number of records to be processed as a parameter to output plugin.
2. Calculated the total number of records processed in batches.
3. After all the batches were processed, I calculated the difference left out by batch processing and loaded them in one shot.

**Customized code:**

def initialize(max_length, max_bytes)
          @lock = ReentrantReadWriteLock.new
          @max_length = max_length --Passed total number of incoming records to this parameter
          @batch_size = 128 --defined default batch size as 128
          @num_processed_records = 0 --counter to count to total number of records processed by batch
          @max_bytes = max_bytes
          clear
end

def enqueue(message)
          @lock.write_lock.lock

          begin
            is_flush_request = message.nil?

            unless is_flush_request
              @batch_size_bytes += message.length
              @batch << message
              @num_processed_records = @num_processed_records + 1 --row counter
            end

            length_met = @batch.length >= @batch_size
            total_length_met = @max_length - @num_processed_records == 0 --flag to indicate that last bunch left out by batch processing
            size_met = @batch_size_bytes >= @max_bytes

            #is_flush_request || length_met || size_met || total_length_met

            print(@batch.length, "total number of records", @num_processed_records, " ", length_met, " ", size_met, " ", total_length_met, "\n")

            if length_met || size_met || total_length_met
              orig = @batch
              clear

              yield(orig) if block_given?
              return orig
            end

            nil

          ensure
            @lock.write_lock.unlock
          end
        end

**Fixed Batcher.rb Code file:**
[batcher.txt](https://github.com/logstash-plugins/logstash-output-google_bigquery/files/3413351/batcher.txt)

**Log output:**

[Log File.txt](https://github.com/logstash-plugins/logstash-output-google_bigquery/files/3413345/Log.File.txt)

I can demo this to you in case needed. I believe sometimes there is an issue counting the number of records processed. Please let me know.

**Comment by ajangus** [comment]
Epic debug @SrikrishnaBingi
