### ISSUE TITLE
Nested fields and arrays for google_bigquery

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-output-google_bigquery#8]
(This issue was originally filed by @thesamet at https://github.com/elastic/logstash-contrib/issues/157)

---

From the documentation of csv_schema it seems like only flat structures are supported. Is there any support planned for supporting nested fields and arrays?

**Comment by josephlewis42** [comment]
`json_schema` should suit this purpose, closing unless someone else discovers otherwise cover.
